apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters: {}
      selector:
        matchExpressions:
          - key: server
            operator: In
            values:
              - https://kubernetes.default.svc
  template:
    metadata:
      name: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/blakepettersson/argocd-deploy.git
        path: .
        targetRevision: main
        helm:
          valueFiles:
            - 'values.yaml'
      destination:
        namespace: argocd
        server: '{{.server}}'
      #syncPolicy:
      #  automated:
      #    prune: true
      #    selfHeal: true